app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "https://slowpitchlab.mattmartiny.com",
    ],
    allow_credentials=False,
    allow_methods=["*"],
    allow_headers=["*"],
)